//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.JavascriptExecutor;
//
//import java.util.*;
//
//public class Test02Test {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void test02() {
//    driver.get("https://front.serverest.dev/login");
//    driver.manage().window().setSize(new Dimension(1296, 688));
//    driver.findElement(By.linkText("Cadastre-se")).click();
//    driver.findElement(By.id("nome")).click();
//    driver.findElement(By.id("nome")).sendKeys("menin");
//    driver.findElement(By.id("email")).click();
//    driver.findElement(By.id("email")).sendKeys("menin2@gmail.com");
//    driver.findElement(By.id("password")).click();
//    driver.findElement(By.id("password")).sendKeys("asasas");
//    driver.findElement(By.id("administrador")).click();
//    driver.findElement(By.cssSelector(".btn-primary")).click();
//  }
//}
